REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM social_app_user;
REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public FROM social_app_user;
REVOKE USAGE ON SCHEMA public FROM social_app_user;
